### PR TITLE
Ria 3745 noc

### PR DESCRIPTION
**Pull request by bradsorour**
### JIRA link (if applicable) ###

[RIA-3745](https://tools.hmcts.net/jira/browse/RIA-3745)

### Change description ###

See Jira

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by makowalski — DISMISSED** [review]
LGTM

**Review by Srihari-Nakkala — DISMISSED** [review]
LGTM

**Comment by bradsorour** [comment]
Do not merge until tested against latest CCD and ExUI images.

**Review by makowalski — APPROVED** [review]
LGTM

**Pull request merged**
